services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel-hexagonal-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - laravel-hexagonal-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel-hexagonal-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-hexagonal-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-hexagonal-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_hexagonal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-hexagonal-network

  redis:
    image: redis:alpine
    container_name: laravel-hexagonal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-hexagonal-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-hexagonal-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel-hexagonal-network
    depends_on:
      - mysql

networks:
  laravel-hexagonal-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
